application: clikcare-stage
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: "2.6"
  
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /admin/.*
  script: main.application
  login: admin
  
- url: /patient/.*
  script: main.application
  login: required
  
- url: /.*
  script: main.application

- url: /_ah/login_required
  script: login.application
