application: veosan-stage
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# for backup/restore
builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "2.6"
  
- name: webapp2
  version: latest
  
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: optional

- url: /assets
  static_dir: assets
  secure: optional
  
- url: /admin/.*
  script: main.application
  login: admin
  secure: always

- url: /sales/.*
  script: main.application
  login: admin

- url: /login
  script: main.application
  secure: always

- url: /login/.*
  script: main.application
  secure: always

- url: /provider/.*
  script: main.application
  secure: always

- url: /.*
  script: main.application
  

